{{- if and .Values.enabled .Values.persistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "provisioner.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "provisioner.name" . }}
{{- include "provisioner.labels" . | indent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistentVolumeClaim.storageClass }}
{{- if .Values.persistentVolumeClaim.annotations }}
{{ toYaml .Values.persistentVolumeClaim.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.persistentVolumeClaim.storageClass }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
{{- end }}
  accessModes:
{{ toYaml .Values.persistentVolumeClaim.accessModes | indent 4 }}
{{- if .Values.persistentVolumeClaim.size }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
{{- end -}}
{{- end -}}
