{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "operator.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "operator.name" . }}
{{- include "operator.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "operator.name" . }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "operator.name" . }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
{{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
      containers:
      - name: {{ template "operator.name" . }}
        image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.log.format }}
          - --zap-encoder={{ .Values.log.format }}
        {{- end }}
        {{- if .Values.log.level }}
          - --zap-level={{ .Values.log.level }}
        {{- end }}
        {{- if .Values.log.devel }}
          - --zap-devel
        {{- end }}
    {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
    {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPOTINST_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "operator.secretName" . }}
              key: token
        - name: SPOTINST_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ template "operator.secretName" . }}
              key: account
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8380
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8380
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
      serviceAccountName: {{ template "operator.serviceAccountName" . }}
      dnsPolicy: {{ .Values.dns.policy }}
{{- if .Values.dns.config }}
      dnsConfig:
{{ toYaml .Values.dns.config | indent 8 }}
{{- end}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
