{{- if and .Values.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "operator.fullname" . }}-psp
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "operator.name" . }}
{{- include "operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "operator.fullname" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ template "operator.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
