{{- if index .Values "ocean-network-client" "deployChart" -}}
{{- $values := index .Values "ocean-network-client" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ocean-network-client.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ocean-network-client.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ocean-network-client.selectorLabels" . | nindent 6 }}
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        {{- include "ocean-network-client.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      hostPID: true
      tolerations:
        {{- toYaml $values.tolerations | nindent 6 }}
      nodeSelector:
        {{- include "ocean-network-client.node-selector.labels" . | nindent 8 }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      serviceAccountName: {{ include "ocean-network-client.fullname" . }}
      terminationGracePeriodSeconds: 30
      {{- with $values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "spotinst-ocean-network-client"
          image: {{ $values.image.repository }}:{{ $values.image.tag | default .Chart.AppVersion }}
          securityContext:
            privileged: true
            capabilities:
              drop: ["all"]
              add: [ "NET_ADMIN", "SYS_ADMIN"] # bpf need SYS_ADMIN network netlink need NET_ADMIN
          imagePullPolicy: {{ $values.image.pullPolicy }}
          resources:
            {{- toYaml $values.resources | nindent 12 }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          env:
            - name: REPORT_INTERVAL
              value: "60"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPOTINST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ocean-kubernetes-controller.secretName" . }}
                  key: token
                  optional: true
            - name: SPOTINST_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: {{ include "ocean-kubernetes-controller.secretName" . }}
                  key: account
                  optional: true
            - name: SPOTINST_TOKEN_LEGACY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocean-kubernetes-controller.configMapName" . }}
                  key: spotinst.token
                  optional: true
            - name: SPOTINST_ACCOUNT_LEGACY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocean-kubernetes-controller.configMapName" . }}
                  key: spotinst.account
                  optional: true
            - name: CLUSTER_IDENTIFIER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocean-kubernetes-controller.configMapName" . }}
                  key: spotinst.cluster-identifier
                  optional: true
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CILIUM_CNI_TUNNEL_MODE
              valueFrom:
                configMapKeyRef:
                  key: tunnel
                  name: cilium-config
                  optional: true
            {{- if eq (include "ocean-network-client.isDevEnv" .)  "true" }}
            - name: ENV_DEV
              value: "true"
            {{- end }}
{{- end }}