apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "ocean-vpa.fullname" . }}-webhook-config
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "ocean-vpa.labels" . | nindent 4 }}
  {{- with .Values.admissionController.mutatingWebhookConfiguration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "ocean-vpa.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: vpa.k8s.io
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
