apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ include "ocean-vpa.fullname" . }}-admission-certgen-secret-delete
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
  labels:
    app.kubernetes.io/component: admission-certgen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocean-vpa.fullname" . }}-secret-delete
subjects:
  - kind: ServiceAccount
    name: {{ include "ocean-vpa.fullname" . }}-secret-delete
    namespace: {{ .Release.Namespace }}
