apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocean-vpa.fullname" . }}-admission-controller
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "ocean-vpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admissionController.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      {{- include "ocean-vpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.admissionController.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/component: admission-controller
        {{- include "ocean-vpa.selectorLabels" . | nindent 8 }}
        {{- with .Values.admissionController.podLabels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "ocean-vpa.serviceAccountName" . }}-admission-controller
      securityContext:
        {{- toYaml .Values.admissionController.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.admissionController.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.admissionController.image.repository (.Values.admissionController.image.tag | default .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.admissionController.image.pullPolicy }}
          args:
            - --register-webhook=false
            - --webhook-service={{ include "ocean-vpa.fullname" . }}-webhook
            - --client-ca-file=/etc/tls-certs/ca
            - --tls-cert-file=/etc/tls-certs/cert
            - --tls-private-key=/etc/tls-certs/key
            - --feature-gates=InPlaceOrRecreate={{ .Values.featureGates.inPlaceOrRecreate }}
            {{- range $key, $value := .Values.admissionController.extraArgs}}
            - --{{ $key }}={{ $value }}
            {{- end }}
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls-certs"
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.admissionController.httpPort | default 8000 }}
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.admissionController.resources | nindent 12 }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ include "ocean-vpa.webhook.secret" . }}
            {{- with .Values.admissionController.tlsSecretKeys }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
      {{- with .Values.admissionController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
