apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ include "ocean-vpa.fullname" . }}-secret-delete
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
  labels:
    app.kubernetes.io/component: admission-certgen
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete