# configuration file for https://github.com/helm/chart-testing
# chart-repos:
#   - stable=https://charts.helm.sh/stable
#   - incubator=https://charts.helm.sh/incubator
target-branch: main
helm-extra-args: --debug
debug: true
excluded-charts:
- wave-operator