{{- if and .Values.caBundleSecret .Values.caBundleSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-metric-exporter.caBundleSecretName" . }}
  namespace: {{ include "ocean-metric-exporter.namespace" . }}
  labels:
  {{- include "ocean-metric-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "ocean-metric-exporter.caBundleSecretKey" . | nindent 2 -}}: {{ required "`caBundleSecret.data` must be specified if `caBundleSecret.create` is `true`" .Values.caBundleSecret.data | b64enc }}
{{- end }}
