apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocean-metric-exporter.deploymentName" . }}
  namespace: {{ include "ocean-metric-exporter.namespace" . }}
  labels:
    {{- include "ocean-metric-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocean-metric-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ocean-metric-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: spot-ocean-metric-exporter
        ports:
        - containerPort: 5050
          name: exporter
        env:
        - name: SPOTINST_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-metric-exporter.secretName" . }}
              key: token
              optional: true
        - name: SPOTINST_TOKEN_LEGACY
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-metric-exporter.configMapName" . }}
              key: spotinst.token
              optional: true
        - name: SPOTINST_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-metric-exporter.secretName" . }}
              key: account
              optional: true
        - name: SPOTINST_ACCOUNT_LEGACY
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-metric-exporter.configMapName" . }}
              key: spotinst.account
              optional: true
        - name: CLUSTER_IDENTIFIER
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-metric-exporter.configMapName" . }}
              key: spotinst.cluster-identifier
        - name: BASE_SPOTINST_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-metric-exporter.configMapName" . }}
              key: base-url
              optional: true
        - name: PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-metric-exporter.configMapName" . }}
              key: proxy-url
              optional: true
        - name: USER_ENV_CERTIFICATES
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-metric-exporter.caBundleSecretName" . }}
              key: userEnvCertificates.pem
              optional: true
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 