{{ if include "ocean-metric-exporter.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-metric-exporter.secretName" . }}
  namespace: {{ include "ocean-metric-exporter.namespace" . }}
type: Opaque
data:
  token: {{ .Values.spotinst.token | b64enc }}
  account: {{ .Values.spotinst.account | b64enc }}
{{- end }}