apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-admission-certgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
  labels:
    app.kubernetes.io/component: certgen
    {{- include "ocean-vertical-pod-autoscaler.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-admission-certgen
      labels:
        app.kubernetes.io/component: admission-certgen
        {{- include "ocean-vertical-pod-autoscaler.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-admission-certgen
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: create
          image: {{ printf "%s:%s" .Values.admissionController.certGen.image.repository .Values.admissionController.certGen.image.tag }}
          args:
            - create
            - --host={{ include "ocean-vertical-pod-autoscaler.fullname" . }}-webhook,{{ include "ocean-vertical-pod-autoscaler.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ include "ocean-vertical-pod-autoscaler.webhook.secret" . }}
          resources:
            {{- toYaml .Values.admissionController.certGen.resources | nindent 12 }}
      {{- with .Values.admissionController.certGen.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.certGen.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.certGen.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.certGen.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}

