apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-secret-delete
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "ocean-vertical-pod-autoscaler.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-secret-delete
      labels:
        {{- include "ocean-vertical-pod-autoscaler.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-admission-certgen
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: secret-delete
          image: {{ printf "%s:%s" .Values.admissionController.certGen.image.repository .Values.admissionController.certGen.image.tag }}
          args:
            - delete
            - --secret-name={{ include "ocean-vertical-pod-autoscaler.webhook.secret" . }}
            - --namespace={{ .Release.Namespace }}
            - --log-level=debug
          resources:
            {{- toYaml .Values.admissionController.certGen.resources | nindent 12 }}
      {{- with .Values.admissionController.certGen.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.certGen.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.certGen.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionController.certGen.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
