apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-webhook-config
  labels:
    app.kubernetes.io/component: admission-controller
    {{- include "ocean-vertical-pod-autoscaler.labels" . | nindent 4 }}
  {{- with .Values.admissionController.mutatingWebhookConfiguration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "ocean-vertical-pod-autoscaler.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: vpa.k8s.io
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
#      - apiGroups:
#          - autoscaling.k8s.io
#        apiVersions:
#          - '*'
#        operations:
#          - CREATE
#          - UPDATE
#        resources:
#          - verticalpodautoscalers
#        scope: '*'
    sideEffects: None
    timeoutSeconds: 30
