{{- if not .Values.spotinst.disableAutoUpdate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "auto-updater.fullname" . }}
  labels:
  {{- include "auto-updater.labels" . | nindent 4 }}
rules:
# Auto Updater requires
- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources: [ "rolebindings" ]
  resourceNames: [ {{ include "auto-updater.fullname" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources: [ "roles" ]
  resourceNames: [ {{ include "auto-updater.fullname" . }} ]
  verbs: [ "get", "patch", "escalate", "bind" ]
- apiGroups: [ "" ]
  resources: [ "serviceaccounts" ]
  resourceNames: [ {{ include "auto-updater.fullname" . }} ]
  verbs: [ "get", "patch" ]
# Helm Management (resource name not required because the name is dynamic)
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "create", "get", "update", "list", "delete" ]
# Required to monitor the deployments rollout after the upgrade
# (resource name not required because the name is dynamic)
- apiGroups: [ "apps" ]
  resources: [ "replicasets" ]
  verbs: [ "list", "watch" ]

# Controller requires
- apiGroups: [ "apps" ]
  resources: [ "deployments" ]
  resourceNames: [ {{ include "ocean-right-sizing-controller.fullname" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  resourceNames: [ {{ include "ocean-right-sizing-controller.configMapName" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  resourceNames: [ {{ include "ocean-right-sizing-controller.secretName" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "" ]
  resources: [ "serviceaccounts" ]
  resourceNames: [ {{ include "ocean-right-sizing-controller.serviceAccountName" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources: [ "roles" ]
  resourceNames: [ {{ include "ocean-right-sizing-controller.fullname" . }} ]
  verbs: [ "get", "patch", "escalate", "bind" ]
- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources: [ "rolebindings" ]
  resourceNames: [ {{ include "ocean-right-sizing-controller.fullname" . }} ]
  verbs: [ "get", "patch" ]
{{- if and (ne .Release.Namespace "kube-system") .Values.resourceQuota.enabled }}
- apiGroups: [ "" ]
  # Cannot limit to specific resource name due to limitation with K8s RBAC.
  # We need to create this resource with the auto-updater and it will not allow
  # 'create' verb if we limit to specific resource name.
  # resourceNames: [ {{ include "ocean-right-sizing-controller.fullname" . }} ]
  resources: [ "resourcequotas" ]
  verbs: [ "get", "patch", "create" ]
{{- end }}

# Metrics Server requires
{{- if (index .Values "metrics-server" "deployChart") }}
- apiGroups: [ "" ]
  resources: [ "serviceaccounts" ]
  resourceNames: [ {{ include "metrics-server.serviceAccountName" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "" ]
  resources: [ "services" ]
  resourceNames: [ {{ include "metrics-server.fullname" . }} ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments" ]
  resourceNames: [ {{ include "metrics-server.fullname" . }} ]
  verbs: [ "get", "patch" ]
{{- end }}

# Ocean VPA requires
{{- if (index .Values "ocean-vpa" "deployChart") }}
- apiGroups: [ "" ]
  resources: [ "serviceaccounts" ]
  resourceNames: [ {{ include "ocean-vpa.serviceAccountName" . }}-admission-controller, {{ include "ocean-vpa.serviceAccountName" . }}-updater ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "" ]
  resources: [ "services" ]
  resourceNames: [ {{ include "ocean-vpa.fullname" . }}-webhook ]
  verbs: [ "get", "patch" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments" ]
  resourceNames: [ {{ include "ocean-vpa.fullname" . }}-updater, {{ include "ocean-vpa.fullname" . }}-admission-controller ]
  verbs: [ "get", "patch" ]
{{- end }}
{{- end }}