{{ if .Values.webhook.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "spark-operator.fullname" . }}-webhook"
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - "{{ include "spark-operator.fullname" . }}-webhook.{ .Release.Namespace }}.svc"
  - "{{ include "spark-operator.fullname" . }}-webhook.{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: "{{ .Values.webhook.certIssuer }}"
  secretName: spark-webhook-certs
{{ end }}
