{{- if not .Values.spotinst.disableAutoUpdate }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auto-updater.serviceAccountName" . }}
  labels:
    {{- include "auto-updater.labels" . | nindent 4 }}
  {{- with .Values.autoUpdate.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}