apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: wave-admission-control
  labels:
    {{- include "wave-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/wave-admission-control
webhooks:
- name: pod.spark.wave.spot.io
  clientConfig:
    service:
      name: wave-admission-control
      namespace: {{ .Release.Namespace }}
      path: "/mutate/pod"
  failurePolicy: Ignore
  objectSelector:
    matchExpressions:
      - key: spark-role
        operator: Exists
      - key: spark-app-selector
        operator: Exists
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
- name: configmap.spark.wave.spot.io
  clientConfig:
    service:
      name: wave-admission-control
      namespace: {{ .Release.Namespace }}
      path: "/mutate/configmap"
  failurePolicy: Ignore
  # spark config-maps don't have labels, we'll just have to look at all of them :(
  # https://github.com/apache/spark/blob/527cd3fc3aac40f84ba8eee291e1a955e03f7665/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/KubernetesClientApplication.scala#L169
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["configmaps"]
    scope: "Namespaced"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  # important to set this to a low value
  timeoutSeconds: 5
