apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ocean-right-sizing-controller.fullname" . }}
  labels:
  {{- include "ocean-right-sizing-controller.labels" . | nindent 4 }}
rules:
  # ---------------------------------------------------------------------------
  # feature: ocean/readonly
  # ---------------------------------------------------------------------------
- apiGroups: [ "" ]
  resources: [ "pods", "nodes", "services", "namespaces", "replicationcontrollers", "limitranges", "events", "persistentvolumes", "persistentvolumeclaims" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments", "daemonsets", "statefulsets", "replicasets" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "storage.k8s.io" ]
  resources: [ "storageclasses" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "batch" ]
  resources: [ "jobs", "cronjobs" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "policy" ]
  resources: [ "poddisruptionbudgets" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "metrics.k8s.io" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "autoscaling" ]
  resources: [ "horizontalpodautoscalers" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "autoscaling.k8s.io" ]
  resources: [ "verticalpodautoscalers" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "node.k8s.io" ]
  resources: [ "runtimeclasses" ]
  verbs: [ "get", "list", "watch" ]
- nonResourceURLs: [ "/version/", "/version" ]
  verbs: [ "get" ]

  # ---------------------------------------------------------------------------
  # feature: controller/leader-election (high-availability)
  # ---------------------------------------------------------------------------
- apiGroups: [ "coordination.k8s.io" ]
  resources: [ "leases" ]
  verbs: [ "get","list","patch","update","create","delete" ]

  # ---------------------------------------------------------------------------
  # feature: automatic right-sizing
  # ---------------------------------------------------------------------------
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers", "verticalpodautoscalers/status"]
  verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["patch", "update"]
- apiGroups: [ "" ]
  resources: [ "pods"]
  verbs: [ "get", "list", "patch", "update", "create", "delete" ]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
  verbs: [ "get", "list", "watch", "patch", "update" ]