{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-right-sizing-controller.secretName" . }}
  labels:
  {{- include "ocean-right-sizing-controller.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "`spotinst.token` must be specified" .Values.spotinst.token | b64enc }}
  account: {{ required "`spotinst.account` must be specified" .Values.spotinst.account | b64enc }}
{{- end }}
