apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ include "ocean-admission-controller.fullname" . }}-secret-delete
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
  labels:
    {{- include "ocean-admission-controller.certgenLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete