name: enterprise-gateway
description: A helm chart to deploy Jupyter Enterprise Gateway
version: 2.5.0
apiVersion: v1
icon: https://avatars1.githubusercontent.com/u/7388996?s=200&v=4
home: https://jupyter.org/enterprise_gateway
sources:
  - https://github.com/jupyter/enterprise_gateway
kubeVersion: '>=1.11.0-0'
maintainers:
  - name: ntfrnzn
    email: nate.franzen@netapp.com
