{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocean-kubernetes-controller.configMapName" . }}
  labels:
  {{- include "ocean-kubernetes-controller.labels" . | nindent 4 }}
data:
  spotinst.cluster-identifier: {{ required "`spotinst.clusterIdentifier` must be specified" .Values.spotinst.clusterIdentifier }}
  base-url: {{ default "" .Values.spotinst.baseUrl | quote }}
  proxy-url: {{ default "" .Values.spotinst.proxyUrl | quote }}
  leader-election: {{ gt (int .Values.replicas) 1 | quote }}
  disable-auto-update: {{ default "false" .Values.spotinst.disableAutoUpdate | quote }}
  enable-csr-approval: {{ default "false" .Values.spotinst.enableCsrApproval | quote }}
  {{- if not .Values.spotinst.disableAutoUpdate }}
  auto-update.job: |
    {{- include "auto-updater.job" . | nindent 4 }}
  {{- end }}
{{- end }}
