{{- if not .Values.spotinst.disableAutoUpdate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocean-kubernetes-controller.fullname" . }}
  labels:
  {{- include "ocean-kubernetes-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocean-kubernetes-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ocean-kubernetes-controller.serviceAccountName" . }}
{{- end }}
