## Deploy Operator.
##
enabled: true

## Provide a name for `app:` labels.
##
nameOverride: ""

## Provide a name to substitute for the full names of resources.
##
fullnameOverride: ""

## Config Map.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
##
configMap:
  create: true
  name: ""

## Service Account.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  create: true
  name: ""

## Secret.
## ref: https://kubernetes.io/docs/concepts/configuration/secret/
##
secret:
  create: true
  name: ""

## Custom Resource Definitions.
## ref: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
##
customResourceDefinitions:
  ## Deploy CRDs used by Ocean Operator.
  ##
  create: true

  ## Clean up CRDs created by Ocean Operator on delete.
  ##
  cleanup: false

## Labels to add to all resources.
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
labels: {}

## Annotations to add to the pod.
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
annotations: {}

## Security context.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  runAsNonRoot: true
  runAsUser: 1001

## Assign a PriorityClassName to pods if set.
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#pod-priority
##
# priorityClassName: ""

## Define log format ('json' or 'console') and level (0-5).
##
log:
  format: json
  level: 3
  devel: false

## Resource limits & requests.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
##
resources: {}
# limits:
#   cpu: 200m
#   memory: 200Mi
# requests:
#   cpu: 100m
#   memory: 100Mi

## Define which Nodes the Pods are scheduled on.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for use with node taints.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## Assign custom affinity rules to the Ocean Operator.
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/e2e-az-name
  #         operator: In
  #         values:
  #         - e2e-az1
  #         - e2e-az2

## DNS.
## ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
##
dns:
  policy: ClusterFirst
  config:
    # options:
    # - name: ndots
    #   value: "1"

## Image.
## ref: https://kubernetes.io/docs/concepts/containers/images/
##
image:
  repository: spotinst/ocean-operator
  pullPolicy: IfNotPresent

## Hyperkube image to use when cleaning up.
##
hyperkubeImage:
  repository: k8s.gcr.io/hyperkube
  tag: v1.12.1
  pullPolicy: IfNotPresent
