{{- if and .Values.enabled .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "operator.secretName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "operator.name" . }}
{{- include "operator.labels" . | indent 4 }}
type: Opaque
data:
  token: {{ required "spot.token is missing" .Values.global.spot.token | b64enc }}
  account: {{ required "spot.account is missing" .Values.global.spot.account | b64enc }}
{{- end }}
