{{- if .Values.ingress.basicAuth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.basicAuth.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark-history-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  auth: {{ htpasswd  .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password  | b64enc | quote }}
{{- end }}