{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "controller.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "controller.name" . }}
{{- include "controller.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "controller.name" . }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "controller.name" . }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
{{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
      containers:
      - name: {{ template "controller.name" . }}
        image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
    {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
    {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPOTINST_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "controller.secretName" . }}
              key: token
              optional: true
        - name: SPOTINST_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ template "controller.secretName" . }}
              key: account
              optional: true
        - name: SPOTINST_TOKEN_LEGACY
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: spotinst.token
              optional: true
        - name: SPOTINST_ACCOUNT_LEGACY
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: spotinst.account
              optional: true
        - name: CLUSTER_IDENTIFIER
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: clusterIdentifier
        - name: DISABLE_AUTO_UPDATE
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: disableAutoUpdate
        - name: ENABLE_CSR_APPROVAL
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: enableCsrApproval
        - name: BASE_SPOTINST_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: baseUrl
        - name: PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "controller.configMapName" . }}
              key: proxyUrl
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 4401
          initialDelaySeconds: 300
          periodSeconds: 20
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 4401
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
      serviceAccountName: {{ template "controller.serviceAccountName" . }}
      dnsPolicy: {{ .Values.dns.policy }}
{{- if .Values.dns.config }}
      dnsConfig:
{{ toYaml .Values.dns.config | indent 8 }}
{{- end}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
{{- end }}
