{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "controller.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "controller.name" . }}
{{- include "controller.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
