apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-operator.fullname" . }}
  labels:
    {{- include "ocean-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ required "spotinst.token is missing" .Values.spotinst.token | b64enc }}
  account: {{ required "spotinst.account is missing" .Values.spotinst.account | b64enc }}
