{{- if and .Values.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "controller.fullname" . }}
  labels:
    app: {{ template "controller.name" . }}
{{- include "controller.labels" . | indent 4 }}
rules:
  # ---------------------------------------------------------------------------
  # Required for functional operation (read-only).
  # ---------------------------------------------------------------------------
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - namespaces
  - replicationcontrollers
  - limitranges
  - events
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- nonResourceURLs:
  - /version/
  - /version
  verbs:
  - get
  # ---------------------------------------------------------------------------
  # Required by the draining feature and for functional operation.
  # ---------------------------------------------------------------------------
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
  # ---------------------------------------------------------------------------
  # Required by the Spotinst Clean Up feature.
  # ----------------------------------------------------------------------------
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - delete
  # ----------------------------------------------------------------------------
  # Required by the Spotinst CSR Approval feature.
  # ----------------------------------------------------------------------------
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - patch
  - update
  # ---------------------------------------------------------------------------
  # Required by the Spotinst Auto Update feature.
  # ---------------------------------------------------------------------------
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - spotinst-kubernetes-cluster-controller
  resources:
  - clusterroles
  verbs:
  - patch
  - update
  - escalate
  # ---------------------------------------------------------------------------
  # Required by the Spotinst Apply feature.
  # ---------------------------------------------------------------------------
- apiGroups:
  - apps
  resourceNames:
  - spotinst-kubernetes-cluster-controller
  resources:
  - deployments
  verbs:
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - update
  - create
  - delete
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - update
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - create
  - delete
  # ----------------------------------------------------------------------------
  # Required by Spotinst Wave.
  # ----------------------------------------------------------------------------
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - scheduledsparkapplications
  verbs:
  - get
  - list
{{- end }}
