{{- if and .Values.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "controller.fullname" . }}-psp
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "controller.name" . }}
{{- include "controller.labels" . | indent 4 }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ template "controller.fullname" . }}
{{- end }}
