{{- if index .Values "ocean-metric-exporter" "deployChart" -}}
{{- $values := index .Values "ocean-metric-exporter" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocean-metric-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocean-metric-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ $values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocean-metric-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ocean-metric-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: spot-ocean-metric-exporter
        ports:
        - containerPort: 5050
          name: exporter
        env:
        - name: SPOTINST_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-kubernetes-controller.secretName" . }}
              key: token
              optional: true
        - name: SPOTINST_TOKEN_LEGACY
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-kubernetes-controller.configMapName" . }}
              key: spotinst.token
              optional: true
        - name: SPOTINST_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-kubernetes-controller.secretName" . }}
              key: account
              optional: true
        - name: SPOTINST_ACCOUNT_LEGACY
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-kubernetes-controller.configMapName" . }}
              key: spotinst.account
              optional: true
        - name: CLUSTER_IDENTIFIER
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-kubernetes-controller.configMapName" . }}
              key: spotinst.cluster-identifier
        - name: BASE_SPOTINST_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-kubernetes-controller.configMapName" . }}
              key: http-base-url
              optional: true
        - name: PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ocean-kubernetes-controller.configMapName" . }}
              key: proxy-url
              optional: true
        - name: USER_ENV_CERTIFICATES
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-kubernetes-controller.caBundleSecretName" . }}
              key: {{ .Values.caBundleSecret.key }}
              optional: true
        {{- with $values.podEnvVariables }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ $values.image.repository }}:{{ $values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ $values.image.pullPolicy }}
        command: {{ include "ocean-metric-exporter.command" . }}
        args:
        - --categories={{ join "," $values.metricsConfiguration.categories }}
        - --allow-metrics={{ join "," $values.metricsConfiguration.allowMetrics }}
        - --deny-metrics={{ join "," $values.metricsConfiguration.denyMetrics }}
        - --allow-labels={{ join "," $values.metricsConfiguration.allowLabels }}
        - --deny-labels={{ join "," $values.metricsConfiguration.denyLabels }}
        resources:
          {{- toYaml $values.resources | nindent 12 }}
        {{- include "ocean-metric-exporter.probes" . | nindent 8 }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
{{- end }}