{{- if index .Values "ocean-metric-exporter" "deployChart" -}}
{{- $values := index .Values "ocean-metric-exporter" }}
{{- if $values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocean-metric-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocean-metric-exporter.labels" . | nindent 4 }}
spec:
  ports:
  - name: exporter
    port: 5050
    protocol: TCP
    targetPort: exporter
  selector:
    {{- include "ocean-metric-exporter.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
{{- end }}