apiVersion: v2
name: ocean-right-sizing-controller
description: A Helm chart for Ocean Right-Sizing Controller
type: application
version: 0.1.62
appVersion: 2.0.70
kubeVersion: ">=1.20.0-0"
maintainers:
  - name: spotinst
    email: ng-spot-info@netapp.com
icon: https://docs.spot.io/_media/images/spot_mark.png
keywords:
  - spot
  - ocean
  - right-sizing
  - controller
dependencies:
  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.deployChart
  - name: ocean-vpa
    version: 1.0.4
    repository: https://charts.spot.io
    condition: ocean-vpa.deployChart
