apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocean-network-client.configMapName" . }}
data:
  spotinst.cluster-identifier: {{ required "`spotinst.clusterIdentifier` must be specified" .Values.spotinst.clusterIdentifier }}
