{{ if ne .Values.spotinst.clusterIdentifier "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocean-network-client.configMapName" . }}
  namespace: {{ include "ocean-network-client.namespace" . }}
data:
  spotinst.cluster-identifier: {{  .Values.spotinst.clusterIdentifier }}
{{- end }}