{{ if include "ocean-network-client.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-network-client.secretName" . }}
  namespace: {{ include "ocean-network-client.namespace" . }}
type: Opaque
data:
  token: {{  .Values.spotinst.token | b64enc }}
  account: {{  .Values.spotinst.account | b64enc }}
{{- end }}
