apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-network-client.secretName" . }}
  namespace: {{ include "ocean-network-client.namespace" . }}
type: Opaque
data:
  token: {{ required "`spotinst.token` must be specified" .Values.spotinst.token | b64enc }}
  account: {{ required "`spotinst.account` must be specified" .Values.spotinst.account | b64enc }}

