name: Lint and Test Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: .github/ct.yaml

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.0.0
      #   # Only build a kind cluster if there are chart changes to test.
      #   if: steps.lint.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   uses: helm/chart-testing-action@v1.0.0
      #   with:
      #     command: install
      #     config: .github/ct.yaml
