name: Lint Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**
  pull_request:
    paths:
      - charts/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config .github/ct.yaml

      - uses: gabe565/setup-helm-docs-action@v1.0.3
      - run: helm-docs
      - name: Check for changes in docs
        run: git diff --exit-code || (echo "Docs are out of date. Please run 'make docs' and commit the changes." && exit 1)