oceanController:
  # -- (Optional) Namespace where components should be installed.
  namespace: kube-system
  # -- (Optional) Secret name.
  secretName: spotinst-kubernetes-cluster-controller
  # -- (Optional) ConfigMap name.
  configMapName: spotinst-kubernetes-cluster-controller-config
  # -- (Optional) Secret name of CA bundle.
  caBundleSecretName: spotinst-kubernetes-cluster-controller-ca-bundle

# -- (Optional) Replicas.
# Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas
replicaCount: 1

# Image.
# Ref: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- (Optional) Image repository.
  repository: gcr.io/spotinst-artifacts/spot-ocean-metric-exporter
  # -- (Optional) Image pull policy.
  pullPolicy: IfNotPresent
  # -- (Optional) Image pull secrets.
  pullSecrets: []
  # -- (Optional) Image tag. Defaults to `.Chart.AppVersion`.
  tag: ""

# -- (Optional) Pod annotations.
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- (Optional) Resource requests and limits.
# Ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 50Mi

# -- (Optional) Node selector.
nodeSelector: {}

# -- (Optional) Tolerations for nodes that have taints on them.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists

# -- (Optional) Pod scheduling preferences.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Service.
service:
  # -- (Optional) Controls whether a service should be created.
  create: true
